apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitalviz-backend
  labels:
    app: orbitalviz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitalviz-backend
  template:
    metadata:
      labels:
        app: orbitalviz-backend
    spec:
      containers:
      - name: backend
        image: gitlab-registry.nrp-nautilus.io/timothy.sereda/ov/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
---
apiVersion: v1
kind: Service
metadata:
  name: orbitalviz-backend
spec:
  selector:
    app: orbitalviz-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
