apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbitalviz-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  tls:
  - hosts:
    - orbitalviz.nrp-nautilus.io
    secretName: orbitalviz-tls
  rules:
  - host: orbitalviz.nrp-nautilus.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: orbitalviz-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orbitalviz-frontend
            port:
              number: 80
